#!/bin/bash
#PBS -l walltime=72:00:00
#PBS -j oe
#PBS -l nodes=64:ppn=1
#PBS -o loggo.txt
#PBS -N WIPP_scattering_50
#PBS -q batch

#  --mca btl_tcp_if_include p3p2 tells batchnew nodes which network interface to use
#    batch is infiniband (ib0?), batchnew is just a private ethernet network
# mpiexec -np 56 --mca btl_tcp_if_include p3p2 python /shared/users/asousa/WIPP/WIPPv4/run_wipp_MPI.py

#  mpiexec -np 24 python /shared/users/asousa/WIPP/global_precip/global_precip_MPI.py
mpi=/usr/local/bin/mpirun # Which MPI to run
#pyt=/shared/users/prblaes/software/python-2.7.3/bin/python # Which Python to use
pyt=/shared/users/asousa/software/python2/bin/python
cmd=/shared/users/asousa/WIPP/global_precip/global_precip_MPI.py # Which file to run

$mpi $pyt $cmd

